/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package textanalyser;

/**
 *
 * @author parth-patil
 */
public class TextAnalyserJFrame extends javax.swing.JFrame {

    /**
     * Creates new form TextAnalyserJFrame
     */
    public TextAnalyserJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        label1 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        SubmitBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        LinesBtn = new javax.swing.JLabel();
        lengthLabel = new javax.swing.JLabel();
        SpacesBtn = new javax.swing.JLabel();
        TabsBtn = new javax.swing.JLabel();
        WordsBtn = new javax.swing.JLabel();
        linesCount = new javax.swing.JTextField();
        lengthDisplay = new javax.swing.JTextField();
        tabsCount = new javax.swing.JTextField();
        spacesCount = new javax.swing.JTextField();
        wordsCount = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        characterChoice = new javax.swing.JComboBox<>();
        characterCount = new javax.swing.JButton();
        characterCountDisplay = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textCountInput = new javax.swing.JTextField();
        textCountButton = new javax.swing.JButton();
        textCountDisplay = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Courier 10 Pitch", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TEXT ANALYSER");
        jLabel1.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        SubmitBtn.setBackground(new java.awt.Color(255, 102, 102));
        SubmitBtn.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        SubmitBtn.setText("Submit");
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 102, 102));
        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Analysis Report");
        jLabel2.setOpaque(true);

        LinesBtn.setBackground(new java.awt.Color(255, 153, 153));
        LinesBtn.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        LinesBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LinesBtn.setText("Lines");
        LinesBtn.setOpaque(true);

        lengthLabel.setBackground(new java.awt.Color(255, 153, 153));
        lengthLabel.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        lengthLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lengthLabel.setText("Length");
        lengthLabel.setOpaque(true);

        SpacesBtn.setBackground(new java.awt.Color(255, 153, 153));
        SpacesBtn.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        SpacesBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SpacesBtn.setText("Spaces");
        SpacesBtn.setOpaque(true);

        TabsBtn.setBackground(new java.awt.Color(255, 153, 153));
        TabsBtn.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        TabsBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TabsBtn.setText("Tabs");
        TabsBtn.setOpaque(true);

        WordsBtn.setBackground(new java.awt.Color(255, 153, 153));
        WordsBtn.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        WordsBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WordsBtn.setText("Words");
        WordsBtn.setOpaque(true);

        linesCount.setEditable(false);
        linesCount.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        linesCount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        linesCount.setOpaque(true);

        lengthDisplay.setEditable(false);
        lengthDisplay.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        lengthDisplay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lengthDisplay.setOpaque(true);
        lengthDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lengthDisplayActionPerformed(evt);
            }
        });

        tabsCount.setEditable(false);
        tabsCount.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        tabsCount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tabsCount.setOpaque(true);

        spacesCount.setEditable(false);
        spacesCount.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        spacesCount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        spacesCount.setOpaque(true);

        wordsCount.setEditable(false);
        wordsCount.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        wordsCount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wordsCount.setOpaque(true);

        TextArea.setColumns(20);
        TextArea.setLineWrap(true);
        TextArea.setRows(5);
        TextArea.setText("Hello my name is Parth! Elio is an artist. one must find blue bells");
        jScrollPane4.setViewportView(TextArea);

        characterChoice.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        characterChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z" }));
        characterChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                characterChoiceActionPerformed(evt);
            }
        });

        characterCount.setBackground(new java.awt.Color(255, 204, 153));
        characterCount.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        characterCount.setText("Get Count:");
        characterCount.setOpaque(true);
        characterCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                characterCountActionPerformed(evt);
            }
        });

        characterCountDisplay.setEditable(false);
        characterCountDisplay.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N

        jLabel7.setBackground(new java.awt.Color(255, 204, 102));
        jLabel7.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Enter Text :");
        jLabel7.setOpaque(true);

        jLabel8.setBackground(new java.awt.Color(255, 204, 102));
        jLabel8.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Choose a character:");
        jLabel8.setOpaque(true);

        textCountInput.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        textCountInput.setText("el");
        textCountInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCountInputActionPerformed(evt);
            }
        });

        textCountButton.setBackground(new java.awt.Color(255, 204, 153));
        textCountButton.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        textCountButton.setText("Get Count");
        textCountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCountButtonActionPerformed(evt);
            }
        });

        textCountDisplay.setEditable(false);
        textCountDisplay.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SubmitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lengthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lengthDisplay))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LinesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(linesCount))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TabsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tabsCount))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SpacesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spacesCount))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(WordsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wordsCount))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(characterChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(characterCount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(characterCountDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textCountInput)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(textCountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textCountDisplay))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lengthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lengthDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LinesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(linesCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TabsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tabsCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SpacesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spacesCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WordsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wordsCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(characterChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(characterCount)
                            .addComponent(characterCountDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textCountInput, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCountButton)
                    .addComponent(textCountDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel3.setBackground(new java.awt.Color(255, 204, 204));
        jLabel3.setFont(new java.awt.Font("Ubuntu Sans", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DEVELOPED     BY      PARTH PATIL");
        jLabel3.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lengthDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lengthDisplayActionPerformed
        // TODO add your handling code here:
        String inputText = TextArea.getText();
        int length = inputText.length();
        lengthDisplay.setText(""+length);
        
    }//GEN-LAST:event_lengthDisplayActionPerformed

    private void characterCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_characterCountActionPerformed
        // TODO add your handling code here:
        String selectedCharacter = characterChoice.getSelectedItem().toString();
        String inputText = TextArea.getText().toLowerCase();
        int charCount = 0;
        for (int i = 0; i < inputText.length(); i++) {
            if (inputText.charAt(i) == selectedCharacter.charAt(0)) {
                charCount++;
            }
        }
        characterCountDisplay.setText(""+charCount);
    }//GEN-LAST:event_characterCountActionPerformed

    private void textCountInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCountInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCountInputActionPerformed

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        // TODO add your handling code here:
        String inputText = TextArea.getText();
        int length = inputText.length();
        lengthDisplay.setText("" + length);

        int lines = inputText.split("\n", -1).length;
        linesCount.setText("" + lines);

        int tabCount = inputText.split("\t", -1).length - 1;
        tabsCount.setText("" + tabCount);
        
        int spaceCount = inputText.split(" ").length - 1;
        spacesCount.setText("" + spaceCount);
        
        int wordCount;
        if (inputText.trim().isEmpty()) {
            wordCount = 0;
        } else {
            wordCount = inputText.split("\\s+").length;
        }
        wordsCount.setText("" + wordCount);

    }//GEN-LAST:event_SubmitBtnActionPerformed

    private void textCountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCountButtonActionPerformed
        // TODO add your handling code here:
        String searchText = textCountInput.getText().toLowerCase();
        String fullText = TextArea.getText().toLowerCase();
        int count = 0;
        int index = 0;
        while ((index = fullText.indexOf(searchText, index)) != -1) {
            count++;
            index += searchText.length();
            textCountDisplay.setText("" + count);
        }
    }//GEN-LAST:event_textCountButtonActionPerformed

    private void characterChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_characterChoiceActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_characterChoiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TextAnalyserJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TextAnalyserJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TextAnalyserJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TextAnalyserJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TextAnalyserJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LinesBtn;
    private javax.swing.JLabel SpacesBtn;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JLabel TabsBtn;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JLabel WordsBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> characterChoice;
    private javax.swing.JButton characterCount;
    private javax.swing.JTextField characterCountDisplay;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private java.awt.Label label1;
    private javax.swing.JTextField lengthDisplay;
    private javax.swing.JLabel lengthLabel;
    private javax.swing.JTextField linesCount;
    private javax.swing.JTextField spacesCount;
    private javax.swing.JTextField tabsCount;
    private javax.swing.JButton textCountButton;
    private javax.swing.JTextField textCountDisplay;
    private javax.swing.JTextField textCountInput;
    private javax.swing.JTextField wordsCount;
    // End of variables declaration//GEN-END:variables
}
