/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.gradleproject2;

public class Media {
    
    String name;
    String releaseDate;
    long productionCost;
    long moneyInSales;

    public Media(String name, String releaseDate, long productionCost, long moneyInSales) {
        this.name = name;
        this.releaseDate = releaseDate;
        this.productionCost = productionCost;
        this.moneyInSales = moneyInSales;
    }
    
    
    public static void main(String[] args) {
            LiveAction Mickey17 = new LiveAction("Robert Pattinson", "BJH", "2:30:00 mins", "Mickey17", "5th Dec 2003", 50000000, 1000000000);
            System.out.println(Mickey17);
    }

    
}
